import numpy as np
import pandas as pd
from collections import Counter
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import (
    silhouette_score,
    davies_bouldin_score,
    calinski_harabasz_score,
    pairwise_distances
)

class ClusteringValidator:
    """
    Computes a comprehensive suite of validation metrics for clustering results.
    """
    def __init__(self, X: np.ndarray, labels: np.ndarray, 
                 true_labels: np.ndarray = None, motif_lengths: np.ndarray = None):
        """
        Args:
            X: Feature matrix or equal-length raw motifs (n_samples, n_features).
               Note: Variance-based metrics (CH, Gap) require coordinates, not distance matrices.
            labels: Cluster assignments for each sample.
            true_labels: Ground truth labels (optional, for Purity).
            motif_lengths: Array of original motif lengths (optional, for Length Distribution).
        """
        self.X = X
        self.labels = labels
        self.true_labels = true_labels
        self.lengths = motif_lengths
        
        # Filter out noise points (-1) typically generated by DBSCAN/HDBSCAN
        # Most internal metrics break or are heavily skewed if noise is treated as a cluster
        self.valid_idx = self.labels != -1
        self.clean_X = self.X[self.valid_idx]
        self.clean_labels = self.labels[self.valid_idx]
        self.n_clusters = len(np.unique(self.clean_labels))

    def _check_validity(self):
        if self.n_clusters < 2:
            return False
        return True

    # ==========================================
    # 1. STANDARD SKLEARN METRICS
    # ==========================================
    def compute_silhouette(self) -> float:
        if not self._check_validity(): return -1.0
        return silhouette_score(self.clean_X, self.clean_labels)

    def compute_davies_bouldin(self) -> float:
        """Lower is better. Measures average similarity between clusters and their most similar one."""
        if not self._check_validity(): return float('inf')
        return davies_bouldin_score(self.clean_X, self.clean_labels)

    def compute_calinski_harabasz(self) -> float:
        """Higher is better. Ratio of between-cluster dispersion to within-cluster dispersion."""
        if not self._check_validity(): return 0.0
        return calinski_harabasz_score(self.clean_X, self.clean_labels)

    # ==========================================
    # 2. CUSTOM DISTANCE-BASED METRICS
    # ==========================================
    def compute_dunn_index(self) -> float:
        """
        Higher is better. Ratio of the smallest distance between observations not in the 
        same cluster to the largest intra-cluster distance.
        """
        if not self._check_validity(): return 0.0
        
        distances = pairwise_distances(self.clean_X)
        max_intra_cluster_dist = 0.0
        min_inter_cluster_dist = float('inf')

        unique_labels = np.unique(self.clean_labels)
        
        for i in unique_labels:
            idx_i = np.where(self.clean_labels == i)[0]
            
            # Max intra-cluster distance
            if len(idx_i) > 1:
                intra_dist = np.max(distances[idx_i][:, idx_i])
                max_intra_cluster_dist = max(max_intra_cluster_dist, intra_dist)
            
            # Min inter-cluster distance
            for j in unique_labels:
                if i >= j: continue
                idx_j = np.where(self.clean_labels == j)[0]
                inter_dist = np.min(distances[idx_i][:, idx_j])
                min_inter_cluster_dist = min(min_inter_cluster_dist, inter_dist)

        if max_intra_cluster_dist == 0:
            return float('inf')
            
        return min_inter_cluster_dist / max_intra_cluster_dist

    def compute_gap_statistic(self, n_refs: int = 5) -> float:
        """
        Estimates the Gap Statistic for the current clustering assignment.
        Compares the within-cluster dispersion to a uniform null reference distribution.
        """
        if not self._check_validity(): return 0.0
        
        # Calculate within-cluster dispersion (Wk) of actual data
        def compute_dispersion(data, lbls):
            dispersion = 0.0
            for k in np.unique(lbls):
                cluster_data = data[lbls == k]
                if len(cluster_data) > 1:
                    center = np.mean(cluster_data, axis=0)
                    dispersion += np.sum(np.linalg.norm(cluster_data - center, axis=1) ** 2)
            return dispersion

        actual_Wk = compute_dispersion(self.clean_X, self.clean_labels)
        if actual_Wk == 0: return 0.0
        
        # Generate reference distributions and compute expected Wk
        ref_dispersions = []
        min_vals = np.min(self.clean_X, axis=0)
        max_vals = np.max(self.clean_X, axis=0)
        
        for _ in range(n_refs):
            # Uniform bounding box distribution
            ref_data = np.random.uniform(min_vals, max_vals, self.clean_X.shape)
            
            # For a pure gap stat, refit KMeans, but for validation of *these* exact shapes, 
            from sklearn.cluster import KMeans
            km = KMeans(n_clusters=self.n_clusters, n_init=1, random_state=42)
            ref_lbls = km.fit_predict(ref_data)
            
            ref_dispersions.append(compute_dispersion(ref_data, ref_lbls))
            
        expected_log_Wk = np.mean(np.log(ref_dispersions))
        actual_log_Wk = np.log(actual_Wk)
        
        return expected_log_Wk - actual_log_Wk

    # ==========================================
    # 3. EXTERNAL & DEMOGRAPHIC METRICS
    # ==========================================
    def compute_purity(self) -> float:
        """
        Requires ground truth labels. Measures the extent to which clusters 
        contain a single class.
        """
        if self.true_labels is None:
            return None
            
        clean_true = self.true_labels[self.valid_idx]
        total_correct = 0
        
        for cluster_id in np.unique(self.clean_labels):
            # Get true labels for instances in this cluster
            cluster_true_labels = clean_true[self.clean_labels == cluster_id]
            # Find the most frequent true label
            most_common = Counter(cluster_true_labels).most_common(1)[0][1]
            total_correct += most_common
            
        return total_correct / len(self.clean_labels)

    def compute_cluster_size_distribution(self) -> pd.DataFrame:
        """Returns the count and percentage of motifs in each cluster."""
        counts = pd.Series(self.labels).value_counts().sort_index()
        percentages = (counts / len(self.labels)) * 100
        
        df = pd.DataFrame({
            'Cluster': counts.index,
            'Count': counts.values,
            'Percentage (%)': percentages.values
        })
        return df.set_index('Cluster')

    def compute_length_distribution(self) -> pd.DataFrame:
        """
        If original lengths were provided, validates whether the clustering 
        algorithm respected the length constraints (similar lengths together).
        """
        if self.lengths is None:
            return None
            
        df = pd.DataFrame({'Cluster': self.labels, 'Length': self.lengths})
        # Group by cluster and get mean, std, min, and max length
        stats = df.groupby('Cluster')['Length'].agg(['mean', 'std', 'min', 'max']).round(2)
        return stats

    # ==========================================
    # 4. REPORT GENERATION
    # ==========================================
    def generate_report(self) -> dict:
        """Runs all computations and returns a structured dictionary report."""
        report = {
            "Num_Clusters": self.n_clusters,
            "Noise_Points": np.sum(self.labels == -1),
            "Silhouette_Score": self.compute_silhouette(),
            "Davies_Bouldin": self.compute_davies_bouldin(),
            "Calinski_Harabasz": self.compute_calinski_harabasz(),
            "Dunn_Index": self.compute_dunn_index(),
            "Gap_Statistic": self.compute_gap_statistic(),
            "Cluster_Purity": self.compute_purity()
        }
        return report

# ==========================================
# EXECUTION
# ==========================================
if __name__ == "__main__":

    print("Loading real feature matrix for validation...")

    # 1. Load the  dataset
    df = pd.read_csv("data/future_motifs.csv")

    # 2. Extract the true lengths of each motif 
    lengths = df['Shape_Length'].values.astype(int)

    # 3. Extract and scale the numerical features
    feature_cols = [col for col in df.columns if col not in ['Motif_ID', 'Signal_ID']]
    raw_features = df[feature_cols].values

    scaler = StandardScaler()
    X_real = scaler.fit_transform(raw_features)

    # 4. Generate predicted labels by running a clustering algorithm
    # (K-Means with 5 clusters here to give the validator something to score)
    print("Running K-Means to generate cluster predictions...")
    kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
    pred_lbls = kmeans.fit_predict(X_real)

    print(f"Data loaded: {X_real.shape[0]} motifs ready for validation scoring.")
    # Run Validator
    validator = ClusteringValidator(X=X_real, labels=pred_lbls, 
                                    true_labels=None, motif_lengths=lengths)
    
    print("\n=== CLUSTERING VALIDATION REPORT ===")
    metrics = validator.generate_report()
    for k, v in metrics.items():
        if v is not None:
            print(f"{k.replace('_', ' ')}: {v:.4f}" if isinstance(v, float) else f"{k.replace('_', ' ')}: {v}")
            
    print("\n--- Cluster Size Distribution ---")
    print(validator.compute_cluster_size_distribution())
    
    print("\n--- Motif Length Distribution by Cluster ---")
    print(validator.compute_length_distribution())